### ISSUE TITLE
Using redis-commander in docker-compose returns error

### ISSUE THREAD

**Issue by felixerdy** [tidwall/tile38#438]
I'd like to use [redis-commander](https://github.com/joeferner/redis-commander) to view contents in a web gui using the following docker-compose file:

```
version: "3"
services:
  tile38:
    image: tile38/tile38:latest
    ports:
      - 9851:9851
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=tile38
      - REDIS_PORT=9851
    ports:
      - "8081:8081"
    depends_on:
      - tile38
```

I get the following logs / error:
```
tile38_1           |
tile38_1           |    _______ _______
tile38_1           |   |       |       |
tile38_1           |   |____   |   _   |   Tile38 1.16.4 (96dc1d4) 64 bit (amd64/linux)
tile38_1           |   |       |       |   Port: 9851, PID: 1
tile38_1           |   |____   |   _   |
tile38_1           |   |       |       |   tile38.com
tile38_1           |   |_______|_______|
tile38_1           |
tile38_1           | 2019/03/22 18:19:45 [INFO] Server started, Tile38 version 1.16.4, git 96dc1d4
tile38_1           | 2019/03/22 18:19:45 [INFO] AOF loaded 151 commands: 0.02s, 6939/s, 488 KB/s
tile38_1           | 2019/03/22 18:19:45 [INFO] Ready to accept connections at [::]:9851
redis-commander_1  | Creating custom redis-commander config '/redis-commander/config/local-production.json'.
redis-commander_1  | node ./bin/redis-commander --redis-port 9851 --redis-host tile38
redis-commander_1  | No Save: false
redis-commander_1  | listening on  0.0.0.0 : 8081
redis-commander_1  | redis command "command" not supported, cannot build dynamic command list
redis-commander_1  | { ReplyError: ERR unknown command 'select'
redis-commander_1  |     at parseError (/redis-commander/node_modules/redis-parser/lib/parser.js:179:12)
redis-commander_1  |     at parseType (/redis-commander/node_modules/redis-parser/lib/parser.js:302:14) command: { name: 'select', args: [ '0' ] } }
redis-commander_1 exited with code 0
...
```
